nda:
  label: Acord de Confidentialitate
  url: https://github.com/civictechro/volunt-app/files/1143109/Acord.de.Confiden.ialitate.CivicTechRo.pdf
contract:
  label: Contract de Voluntariat
  url: https://github.com/civictechro/volunt-app/files/1143135/Contract.de.Voluntariat.CivicTechRo.pdf

