common: &common
  digest: membri.civictech.ro

development:
  <<: *common
  mail_url_host: test.civictech.ro

test:
  <<: *common
  mail_url_host: www.example.com

production:
  <<: *common
  mail_url_host: membri.civictech.ro
