# This file defines the project Links
# The YAML item record name is the hash key, so keep it as a correct symbol (smallcase, no spaces, no dashes)
github:
  label: GitHub
  helptext: Link la proiect in GitHub
  placeholder: https://github.com/civictechro/volunt-app

slack:
  label: Slack
  helptext: Link la canalul de Slack
  placeholder: https://civictechro.slack.com/messages/volunt_app/

civictech:
  label: CivicTechRo
  helptext: Link la proiectul public pe civictech.ro
  placeholder: http://civictech.ro/NumeProiect

site:
  label: Site
  helptext: Link la proiectul live, daca e cazul
  placeholder: http://membri.civictech.ro

