# NB: This is an "on-disk" structure. These values exists in the database.
# You cannot change exiting values. If you must, a migration is required.

0:  
  text: Initial
  bgcolor: grey
  textcolor: white

1:
  text: Executie
  bgcolor: green
  textcolor: white

2:
  text: Blocat
  bgcolor: yellow
  textcolor: black

3:
  text: Analiza
  bgcolor: grey
  textcolor: black

4:
  text: Abandonat
  bgcolor: red
  textcolor: white

5:
  text: Failed
  bgcolor: red
  textcolor: black

6:
  text: Productie
  bgcolor: green
  textcolor: yellow

7:
  text: Retras
  bgcolor: gray
  textcolor: white

